### PR TITLE
Add possible disable logs for s3

### PR DESCRIPTION
**Pull request by ByJacob**
## what
* add possible disable create logs bucket and configuration for s3

## why
* sometimes logs for s3 website isn't required :)

## references
* don't create issue

### CODE REVIEW

**Comment by korenyoni** [comment]
@ByJacob our `validate-codeowners` workflow did not run

Are you able to do the following?

```
$ git commit --amend (do not change anything)
$ git push [your origin and branch] --force
```

This will retrigger all of the workflows, including `validate-codeowners`

**Review by korenyoni — DISMISSED** [review]
Looks good to me.

**Comment by ByJacob** [comment]
> @ByJacob our `validate-codeowners` workflow did not run
> 
> Are you able to do the following?
> 
> ```
> $ git commit --amend (do not change anything)
> $ git push [your origin and branch] --force
> ```
> 
> This will retrigger all of the workflows, including `validate-codeowners`

I exec your commands

**Review by korenyoni — APPROVED** [review]

**Pull request merged**
