### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by JaviOverflow**
### What
Fix minor typo

### CODE REVIEW

**Comment by Nuru** [comment]
@JaviOverflow Thank you for suggesting a correction to the documentation. We can include that in a future (separate) PR if you like, but if you want us to accept your PR, you have to do a little more work. 

The source of our documentation is the `README.yaml` file, so changes need to be made there.

Then you generate the `README.md` (and some other documentation) by executing:
```bash
make init
make readme/deps
make readme
```
You may want to run that from inside a [Geodesic](https://github.com/cloudposse/geodesic) container if you do not want to install some of the necessary support (such as the Go language runtime) on your workstation. 

Then you check in the `README.yaml` file along with the updated `*.md` files and if that all looks good, we can accept your PR.

**Comment by aknysh** [comment]
@JaviOverflow 
please update README by executing these commands:

```
make init
make readme/deps
make readme
```

**Pull request merged**
